import { useEffect, useRef, useState } from "react";
import { Info } from "lucide-react";

interface Props {
  className?: string;
  iconSize?: number;
}

export function ModelAttribution({ className = "", iconSize = 11 }: Props) {
  const [open, setOpen] = useState(false);
  const wrapRef = useRef<HTMLSpanElement | null>(null);

  useEffect(() => {
    if (!open) return;
    const onDocClick = (e: MouseEvent) => {
      if (!wrapRef.current?.contains(e.target as Node)) setOpen(false);
    };
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === "Escape") setOpen(false);
    };
    document.addEventListener("mousedown", onDocClick);
    document.addEventListener("keydown", onEsc);
    return () => {
      document.removeEventListener("mousedown", onDocClick);
      document.removeEventListener("keydown", onEsc);
    };
  }, [open]);

  return (
    <span ref={wrapRef} className={`relative inline-flex ${className}`}>
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          setOpen((v) => !v);
        }}
        aria-label="About this analysis"
        aria-expanded={open}
        className="inline-flex items-center justify-center text-white/40 hover:text-white/70 transition-colors cursor-pointer"
      >
        <Info size={iconSize} strokeWidth={1.75} />
      </button>
      {open && (
        <span
          role="tooltip"
          className="absolute z-50 right-0 top-full mt-1.5 w-60 rounded-md border border-white/10 bg-black/90 backdrop-blur px-3 py-2 text-[11px] leading-snug text-white/75 shadow-lg normal-case tracking-normal font-sans"
        >
          Generated by <span className="text-white/90">Gemini 3.1 Pro</span>{" "}
          with web-search grounding. Grounding tends to improve accuracy, but
          the model can still goof, so check the sources. We'll be squashing 
          hallucinations as we identify them but it's been pretty dang accurate so far. 
        </span>
      )}
    </span>
  );
}
